services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/devcontainer.Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - airflow-data:/workspaces/academic-scope-demo/airflow
      - ${HOST_DATA_DIR}:/workspaces/academic-scope-demo/data
    command: sleep infinity

volumes:
  airflow-data:
